#!/bin/sh


mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D19.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D29.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D39.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D49.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D16.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D25.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D34.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D43.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D13.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D22.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D31.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D40.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D49.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D18.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D28.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D38.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D48.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D17.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D27.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D37.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D47.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D13.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D22.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D31.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D40.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D49.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D12.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D22.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D32.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D42.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D17.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D26.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D35.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D44.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D16.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D26.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D36.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D46.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D25.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D34.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D43.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D17.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D26.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D35.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D44.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D15.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D24.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D33.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D42.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D14.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D24.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D34.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D44.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D16.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D25.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D34.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D43.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D15.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D24.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D33.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/D42.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/scala/dupes/scala

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D15.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D24.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D33.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/D42.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/java/dupes/java

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D11.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D21.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D31.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D41.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D15.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D25.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D35.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D45.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D20.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D30.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D40.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D50.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D17.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D26.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D35.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D44.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D13.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D23.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D33.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/D43.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/sql/dupes/sql

mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D13.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D22.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D31.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D40.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
mv /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/D49.java  /Users/brianbarrecchia/repos/java-expert/modules/interview-prep/src/main/java/gotham/asset/mgmt/multiple/choice/questions/debugging/dotnet/dupes/dotnet
